---
title: "PRA 2: Neteja, validació i anàlisi de les dades"
author: "Álvaro Díaz i David Leiva"
date: "13/12/2020"
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

******
# Detalls de l'activitat
******
## Presentació
En aquesta pràctica s’elabora un cas pràctic orientat a aprendre a identificar les dades rellevants
per un projecte analític i usar les eines d’integració, neteja, validació i anàlisi de les mateixes

## Competències
En aquesta pràctica es desenvolupen les següents competències del Màster de Data Science:

* Capacitat d'analitzar un problema en el nivell d'abstracció adequat a cada situació i aplicar les habilitats i coneixements adquirits per abordar-lo i resoldre'l.
* Capacitat per aplicar les tècniques específiques de tractament de dades (integració,transformació, neteja i validació) per al seu posterior anàlisi.

## Objectius
Els objectius concrets d’aquesta pràctica són:

* Aprendre a aplicar els coneixements adquirits i la seva capacitat de resolució de problemes en entorns nous o poc coneguts dintre de contextos més amplis o multidisciplinaris.
* Saber identificar les dades rellevants i els tractaments necessaris (integració, neteja i validació) per dur a terme un projecte analític.
* Aprendre a analitzar les dades adequadament per abordar la informació continguda en les dades.
* Identificar la millor representació dels resultats per tal d’aportar conclusions sobre el problema plantejat en el procés analític.
* Actuar amb els principis ètics i legals relacionats amb la manipulació de dades en funció de l'àmbit d'aplicació.
* Desenvolupar les habilitats d'aprenentatge que els permetin continuar estudiant d'una manera que haurà de ser en gran manera autodirigida o autònoma.
* Desenvolupar la capacitat de cerca, gestió i ús d'informació i recursos en l'àmbit de la ciència de dades.


******
# Resolució
******
## Descripció del dataset
Es realitzarà l'anàlisi exploratori (EDA) del dataset https://archive.ics.uci.edu/ml/datasets/HCC+Survival on es recopila informació de pacients amb carcinoma hepatocelullar (HCC) i la seva supervivència a l'any. 

L'HCC és el tumor hepàtic més comú en els pacients amb hepatopatia crónica. La supervivència d'aquests pacients no només depen de l'estadi tumoral si no que també depen de l'estat funcional del fetge. 

El conjunt de dades HCC es va obtenir en l´'Hospital Universitari de Coïmbra (Portugal) i contenia diversos factors demogràfics, de risc, de laboratori i de supervivència global de 165 pacients reals diagnosticats de HCC. El conjunt de dades conté 49 funcions seleccionades segons les directrius de pràctica clínica EASL-EORTC (Associació Europea per a l’Estudi del Fetge - Organització Europea per a la Recerca i el Tractament del Càncer), que són els habituals en la gestió de HCC.

Es tracta d’un conjunt de dades heterogeni, amb 23 variables quantitatives i 26 variables qualitatives. La variable objectiu és la supervivència a 1 any i es va codificar com a variable binària: 0 (mor) i 1 (viu).

Les variables del dataset són:

* **Gender (Gen)**: [1=Home;0=Dona] Sexe del pacient

* **Symptoms (Sym)**:[1=Si;0=No] Sintomàtic

* **Alcohol (Alc)**: [1=Si;0=No] Hepatopatia alcohòlica

* **Hepatitis B Surface Antigen (HBS)**: [1=Si;0=No] Antigen de superfície de l'hepatitis B present a la sang

* **Hepatitis B e Antigen (HBe)**:[1=Si;0=No] Antigen e de l'hepatitis B present a la sang

* **Hepatitis B Core Antibody (HBC)**: [1=Si;0=No] Anticòs per l'hepatitis B present a la sang

* **Hepatitis C Virus Antibody (HCV)**: [1=Si;0=No] Anticòs per l'hepatitis C present a la sang

* **Cirrhosis (Cir)**: [1=Si;0=No] Estadio avançat d'hepatopatia crónica

* **Endemic Countries (End)**: [1=Si;0=No] Pacient procedent de països amb alta prevalença d'hepatitis vírica

* **Smoking (Smo)**: [1=Si;0=No] Fumador

* **Diabetes (Dia)**: [1=Si;0=No] Diabètic

* **Obesity (Obe)**: [1=Si;0=No] Obesitat

* **Hemochromatosis (Hem)**:[1=Si;0=No] Hemocromatosi

* **Arterial Hypertension (HyA)**: [1=Si;0=No] Hipertensió arterial

* **Chronic Renal Insufficiency(CRI)**: [1=Si;0=No] Insuficiència renal

* **Human Immunodeficiency Virus (HIV)**: [1=Si;0=No] Infecció per HIV

* **Nonalcoholic Steatohepatitis (Ste)**: [1=Si;0=No] Esteatosis hepàtica de origen no alcohòlic

* **Esophageal Varices (Eso)**: [1=Si;0=No] Presència de varius esofàgiges com indicador d'hipertensió portal

* **Splenomegaly (Spl)**: [1=Si;0=No] Augment del tamany de la melsa com indicador d'hipertensió portal

* **Portal Hypertension (PHT)**: [1=Si;0=No] Pacient amb hipertensió arterial coneguda

* **Portal Vein Thrombosis (PVT)**: [1=Si;0=No] Presència de trombosi venosa portal

* **Liver Metastasis (Met)**: [1=Si;0=No] Metàstasi hepàtica

* **Radiological Hallmark (Rad)**: [1=Si;0=No]Comportament radiològic típic per HCC

* **Age at diagnosis (Age)**: Anys d'edat al moment del diagnóstic de HCC

* **Grams of Alcohol per day (gAl)**: Grams d'alcohol ingerit de mitjana al dia

* **Packs of cigarets per year (PCi)**: Número de paquets de cigarrets consumits per any

* **Performance Status (PSt)**: [0=Activo;1=Restringit;2=Asistencia ocasional;3=Asistencia parcial;4=Asistencia total;5=Mort] Escala de l'estat general del pacient oncològic

* **Encephalopathy degree (Enc)**: [1=Cap;2=Grau I/II; 3=Grau III/IV] Grau d'afectació mental de l'hepatopatia

* **Ascites degree (Asc)**: [1=Cap;2=Lleu;3=Moderada a Severa] Grau d'ascitis com a indicador indirecte d'hipertensió  portal

* **International Normalised Ratio (INR)**: Temps de protrombina

* **Alpha-Fetoprotein (ng/mL) (AFe)**: Nivells del marcador tumoral a la sang

* **Haemoglobin (g/dL) (Hae)**: Nivells de Hemoglobina a la sang

* **Mean Corpuscular Volume (MCV)**: Volum corpuscular mig dels eritrocits

* **Leukocytes(G/L) (Leu)**: Concentració de cél.lules blanques en sang

* **Platelets (Pla)**: Concentració de plaquestes en sang

* **Albumin (mg/dL) (Alb)**: Nivelss d'albumina en sang

* **Total Bilirubin(mg/dL) (BiT)**: Nivells de Bilirrubina Total en sang

* **Alanine transaminase (U/L) (ALT)**: Nivells d'ALT en sang

* **Aspartate transaminase (U/L) (AST)**: Nivells d'ASP en sang

* **Gamma glutamyl transferase (U/L) (GGT)**: Nivells gamma-GT en sang

* **Alkaline phosphatase (U/L) (ALP)**: Nivelss de fosfatasa alcalina en sang

* **Total Proteins (g/dL) (Pro)**: Concentració total de proteïnes en sang

* **Creatinine (mg/dL) (Crea)**: Concentració de creatinina en sang

* **Number of Nodules (Nod)**: Número de nóduls d'HCC visualitzats

* **Major dimension of nodule (cm) (DiN)**: Tamany major dels nóduls d'HCC

* **Direct Bilirubin (mg/dL) (BiD)**: Nivells de Bilirrubina Directe en sang

* **Iron (Iro)**: Concentració de ferro en sang

* **Oxygen Saturation (%) (OxS)**: Saturació d'oxigen de la sang

* **Ferritin (ng/mL) (Fer)**: Nivells de ferritina en sang

* **Class Attribute (Class)**:[0=Mort; 1=Viu] Supervivent a l'any del diagnóstic d'HCC


